/**
 * 模块15：统一调用审计实体。
 * 功能：保存requestId、主体、规范化动作、HTTP结果和耗时，明确排除敏感请求内容。
 * 技术栈：Spring Data JPA与只追加日志表。
 */
package com.biz.ontology.auth.audit.model;
import jakarta.persistence.*;import java.time.LocalDateTime;
@Entity@Table(name="audit_log")
public class AuditLogEntity {@Id@GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;@Column(name="request_id",nullable=false,length=64)private String requestId;@Column(name="principal_type",nullable=false,length=20)private String principalType;@Column(name="principal_id",length=100)private String principalId;@Column(nullable=false,length=100)private String action;@Column(name="resource_type",length=50)private String resourceType;@Column(name="resource_id",length=100)private String resourceId;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private AuditResult result;@Column(name="http_method",nullable=false,length=10)private String httpMethod;@Column(nullable=false,length=500)private String path;@Column(name="duration_ms",nullable=false)private long durationMs;@Column(name="client_ip",length=64)private String clientIp;@Column(name="error_code",length=100)private String errorCode;@Column(name="created_at",nullable=false)private LocalDateTime createdAt;
public Long getId(){return id;}public String getRequestId(){return requestId;}public String getPrincipalType(){return principalType;}public String getPrincipalId(){return principalId;}public String getAction(){return action;}public String getResourceType(){return resourceType;}public String getResourceId(){return resourceId;}public AuditResult getResult(){return result;}public String getHttpMethod(){return httpMethod;}public String getPath(){return path;}public long getDurationMs(){return durationMs;}public String getClientIp(){return clientIp;}public String getErrorCode(){return errorCode;}public LocalDateTime getCreatedAt(){return createdAt;}public void setRequestId(String v){requestId=v;}public void setPrincipalType(String v){principalType=v;}public void setPrincipalId(String v){principalId=v;}public void setAction(String v){action=v;}public void setResourceType(String v){resourceType=v;}public void setResourceId(String v){resourceId=v;}public void setResult(AuditResult v){result=v;}public void setHttpMethod(String v){httpMethod=v;}public void setPath(String v){path=v;}public void setDurationMs(long v){durationMs=v;}public void setClientIp(String v){clientIp=v;}public void setErrorCode(String v){errorCode=v;}public void setCreatedAt(LocalDateTime v){createdAt=v;}}
