/**
 * 模块15：审计写入与查询服务。
 * 功能：安全地追加调用记录，并按requestId、主体、动作、结果和时间范围分页查询。
 * 技术栈：Spring事务、Spring Data JPA Specification和统一分页DTO。
 */
package com.biz.ontology.auth.audit.service;
import com.biz.ontology.api.auth.dto.AuditLogResponse;import com.biz.ontology.api.common.PageResponse;import com.biz.ontology.auth.audit.model.*;import com.biz.ontology.auth.audit.repository.AuditLogRepository;import jakarta.persistence.criteria.Predicate;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.time.LocalDateTime;import java.util.*;
@Service
public class AuditService {private final AuditLogRepository repository;public AuditService(AuditLogRepository r){repository=r;}@Transactional(propagation=Propagation.REQUIRES_NEW)public void append(AuditLogEntity log){repository.save(log);}@Transactional(readOnly=true)public PageResponse<AuditLogResponse> page(String requestId,String principalId,String action,AuditResult result,LocalDateTime from,LocalDateTime to,int page,int size){Specification<AuditLogEntity> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();if(requestId!=null&&!requestId.isBlank())p.add(cb.equal(root.get("requestId"),requestId.trim()));if(principalId!=null&&!principalId.isBlank())p.add(cb.equal(root.get("principalId"),principalId.trim()));if(action!=null&&!action.isBlank())p.add(cb.equal(root.get("action"),action.trim()));if(result!=null)p.add(cb.equal(root.get("result"),result));if(from!=null)p.add(cb.greaterThanOrEqualTo(root.get("createdAt"),from));if(to!=null)p.add(cb.lessThanOrEqualTo(root.get("createdAt"),to));return cb.and(p.toArray(Predicate[]::new));};Page<AuditLogEntity> values=repository.findAll(spec,PageRequest.of(page-1,size,Sort.by("createdAt").descending()));return new PageResponse<>(values.stream().map(this::response).toList(),page,size,values.getTotalElements());}private AuditLogResponse response(AuditLogEntity v){return new AuditLogResponse(v.getId(),v.getRequestId(),v.getPrincipalType(),v.getPrincipalId(),v.getAction(),v.getResourceType(),v.getResourceId(),v.getResult(),v.getHttpMethod(),v.getPath(),v.getDurationMs(),v.getClientIp(),v.getErrorCode(),v.getCreatedAt());}}
