/**
 * 模块14：API客户端和API Key生命周期应用服务。
 * 功能：管理客户端、直接权限、一次性Key创建/轮换、吊销和每次请求的实时认证。
 * 技术栈：Spring事务、SecureRandom、HMAC摘要、乐观锁与Spring Data JPA。
 */
package com.biz.ontology.auth.apiclient.service;

import com.biz.ontology.api.auth.dto.*;import com.biz.ontology.api.common.PageResponse;
import com.biz.ontology.auth.apiclient.model.*;import com.biz.ontology.auth.apiclient.repository.*;
import com.biz.ontology.auth.identity.model.*;import com.biz.ontology.auth.identity.service.PermissionService;import com.biz.ontology.auth.token.SecurityTokenProperties;import com.biz.ontology.auth.token.model.TokenStatus;
import com.biz.ontology.common.exception.*;import jakarta.persistence.criteria.Predicate;
import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;import java.time.LocalDateTime;import java.util.*;

@Service
public class ApiClientService {
 private final ApiClientRepository clients;private final ApiClientPermissionRepository relations;private final ApiKeyCredentialRepository credentials;private final PermissionService permissionService;private final ApiClientPermissionService clientPermissions;private final ApiKeyHashService hashes;private final SecurityTokenProperties properties;private final SecureRandom random=new SecureRandom();
 public ApiClientService(ApiClientRepository a,ApiClientPermissionRepository b,ApiKeyCredentialRepository c,PermissionService d,ApiClientPermissionService e,ApiKeyHashService f,SecurityTokenProperties g){clients=a;relations=b;credentials=c;permissionService=d;clientPermissions=e;hashes=f;properties=g;}
 @Transactional(readOnly=true)public PageResponse<ApiClientResponse> page(String keyword,AuthStatus status,int page,int size){Specification<ApiClientEntity> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.isFalse(root.get("deletedFlag")));if(status!=null)p.add(cb.equal(root.get("status"),status));if(keyword!=null&&!keyword.isBlank()){String v="%"+keyword.trim().toLowerCase()+"%";p.add(cb.or(cb.like(cb.lower(root.get("clientId")),v),cb.like(cb.lower(root.get("name")),v)));}return cb.and(p.toArray(Predicate[]::new));};Page<ApiClientEntity> result=clients.findAll(spec,PageRequest.of(page-1,size,Sort.by("clientId")));return new PageResponse<>(result.stream().map(this::response).toList(),page,size,result.getTotalElements());}
 @Transactional(readOnly=true)public ApiClientResponse get(Long id){return response(require(id));}
 @Transactional public ApiClientResponse create(SaveApiClientRequest request){String clientId=request.clientId().trim().toLowerCase();if(clients.existsByClientIdAndDeletedFlagFalse(clientId))throw new BusinessException(PlatformErrorCode.AUTH_CODE_EXISTS);List<AuthPermissionEntity> permissions=permissionService.requireAll(request.permissionCodes());ApiClientEntity client=new ApiClientEntity();client.setClientId(clientId);client.setName(request.name().trim());client.setStatus(AuthStatus.ENABLED);client=clients.saveAndFlush(client);replacePermissions(client.getId(),permissions);return response(client);}
 @Transactional public ApiClientResponse update(Long id,SaveApiClientRequest request){ApiClientEntity client=require(id);version(client.getVersion(),request.version());String clientId=request.clientId().trim().toLowerCase();if(clients.existsByClientIdAndIdNotAndDeletedFlagFalse(clientId,id))throw new BusinessException(PlatformErrorCode.AUTH_CODE_EXISTS);List<AuthPermissionEntity> permissions=permissionService.requireAll(request.permissionCodes());client.setClientId(clientId);client.setName(request.name().trim());relations.deleteByApiClientId(id);relations.flush();replacePermissions(id,permissions);return response(clients.saveAndFlush(client));}
 @Transactional public ApiClientResponse status(Long id,UpdateAuthStatusRequest request){ApiClientEntity client=require(id);version(client.getVersion(),request.version());client.setStatus(request.status());return response(clients.saveAndFlush(client));}
 @Transactional public ApiKeyCreatedResponse createCredential(Long id,CreateApiKeyRequest request){ApiClientEntity client=require(id);if(client.getStatus()!=AuthStatus.ENABLED)throw new BusinessException(PlatformErrorCode.AUTH_PRINCIPAL_DISABLED);LocalDateTime now=LocalDateTime.now();LocalDateTime expires=request.expiresAt()==null?now.plusDays(properties.getApiKeyDefaultDays()):request.expiresAt();if(!expires.isAfter(now))throw new BusinessException(PlatformErrorCode.AUTH_REQUEST_INVALID,"API Key到期时间必须晚于当前时间");if(request.shouldRevokeExisting())credentials.findByApiClientIdAndStatus(id,TokenStatus.ACTIVE).forEach(v->{v.setStatus(TokenStatus.REVOKED);v.setRevokedAt(now);credentials.save(v);});String keyId=randomUrl(12);String secret=randomUrl(32);String raw="ak_"+keyId+"."+secret;ApiKeyCredentialEntity credential=new ApiKeyCredentialEntity();credential.setApiClientId(id);credential.setKeyId(keyId);credential.setKeyPrefix(raw.substring(0,Math.min(16,raw.length())));credential.setSecretHash(hashes.hash(secret));credential.setStatus(TokenStatus.ACTIVE);credential.setExpiresAt(expires);credential.setCreatedAt(now);credentials.saveAndFlush(credential);return new ApiKeyCreatedResponse(client.getClientId(),keyId,credential.getKeyPrefix(),raw,expires);}
 @Transactional public void revoke(Long clientId,String keyId){require(clientId);ApiKeyCredentialEntity credential=credentials.findByKeyId(keyId).filter(v->v.getApiClientId().equals(clientId)).orElseThrow(()->new BusinessException(PlatformErrorCode.AUTH_API_KEY_INVALID));credential.setStatus(TokenStatus.REVOKED);credential.setRevokedAt(LocalDateTime.now());credentials.save(credential);}
 @Transactional public AuthenticatedApiClient authenticate(String raw){String[] parts=parse(raw);ApiKeyCredentialEntity credential=credentials.findByKeyId(parts[0]).orElseThrow(()->new BusinessException(PlatformErrorCode.AUTH_API_KEY_INVALID));if(credential.getStatus()==TokenStatus.REVOKED)throw new BusinessException(PlatformErrorCode.AUTH_API_KEY_REVOKED);LocalDateTime now=LocalDateTime.now();if(credential.getStatus()==TokenStatus.EXPIRED||(credential.getExpiresAt()!=null&&!credential.getExpiresAt().isAfter(now))){credential.setStatus(TokenStatus.EXPIRED);credentials.save(credential);throw new BusinessException(PlatformErrorCode.AUTH_API_KEY_EXPIRED);}if(!hashes.matches(parts[1],credential.getSecretHash()))throw new BusinessException(PlatformErrorCode.AUTH_API_KEY_INVALID);ApiClientEntity client=require(credential.getApiClientId());if(client.getStatus()!=AuthStatus.ENABLED)throw new BusinessException(PlatformErrorCode.AUTH_PRINCIPAL_DISABLED);credential.setLastUsedAt(now);client.setLastUsedAt(now);credentials.save(credential);clients.save(client);return new AuthenticatedApiClient(client,clientPermissions.find(client.getId()),credential.getKeyId());}
 private String[] parse(String raw){if(raw==null||!raw.startsWith("ak_")||!raw.contains("."))throw new BusinessException(PlatformErrorCode.AUTH_API_KEY_INVALID);String body=raw.substring(3);int split=body.indexOf('.');if(split<3||split==body.length()-1)throw new BusinessException(PlatformErrorCode.AUTH_API_KEY_INVALID);return new String[]{body.substring(0,split),body.substring(split+1)};}
 private void replacePermissions(Long id,List<AuthPermissionEntity> permissions){relations.saveAll(permissions.stream().map(p->{ApiClientPermissionEntity r=new ApiClientPermissionEntity();r.setApiClientId(id);r.setPermissionId(p.getId());return r;}).toList());}
 private ApiClientEntity require(Long id){return clients.findByIdAndDeletedFlagFalse(id).orElseThrow(()->new BusinessException(PlatformErrorCode.AUTH_API_CLIENT_NOT_FOUND));}
 private ApiClientResponse response(ApiClientEntity c){List<ApiClientResponse.CredentialSummary> summaries=credentials.findByApiClientIdOrderByCreatedAtDesc(c.getId()).stream().map(v->new ApiClientResponse.CredentialSummary(v.getId(),v.getKeyId(),v.getKeyPrefix(),v.getStatus(),v.getExpiresAt(),v.getLastUsedAt(),v.getCreatedAt())).toList();return new ApiClientResponse(c.getId(),c.getClientId(),c.getName(),c.getStatus(),clientPermissions.find(c.getId()),summaries,c.getLastUsedAt(),c.getVersion(),c.getCreatedAt(),c.getUpdatedAt());}
 private void version(Long actual,Long requested){if(requested==null||!Objects.equals(actual,requested))throw new BusinessException(PlatformErrorCode.OPTIMISTIC_LOCK_CONFLICT);}private String randomUrl(int size){byte[] value=new byte[size];random.nextBytes(value);return Base64.getUrlEncoder().withoutPadding().encodeToString(value);}
 public record AuthenticatedApiClient(ApiClientEntity client,Set<String> permissions,String keyId){}
}
